import PublicFooter from "@/components/PublicFooter";
import PublicHeader, { propNexusWhatsAppUrl } from "@/components/PublicHeader";
import PropertyCard from "@/components/PropertyCard";
import { Property } from "@/lib/property";
import { trpc } from "@/lib/trpc";
import { ArrowDownRight, ArrowUpRight, Building2, CheckCircle2, ChevronRight, MapPin, Search, ShieldCheck, Sparkles, TreePine } from "lucide-react";
import { useMemo, useState } from "react";
import { Link, useLocation } from "wouter";

const heroImage = "/manus-storage/hillside-house_152b67cb.png";

export default function Landing() {
  const [, setLocation] = useLocation();
  const [propertyType, setPropertyType] = useState("All");
  const [listingType, setListingType] = useState<"Sale" | "Rent">("Sale");
  const [searchLocation, setSearchLocation] = useState("");
  const [budget, setBudget] = useState("all");
  const filters = useMemo(() => ({ propertyType: propertyType === "All" ? undefined : propertyType as "House" | "Apartment" | "Land" | "Commercial", listingType, location: searchLocation || undefined, maxPrice: budget === "all" ? undefined : Number(budget) }), [propertyType, listingType, searchLocation, budget]);
  const propertiesQuery = trpc.properties.list.useQuery(undefined);
  const allProperties = (propertiesQuery.data ?? []) as Property[];
  const featured = allProperties.filter(item => item.featured).slice(0, 3);
  const recent = allProperties.slice(3, 9);

  function beginSearch() {
    const params = new URLSearchParams();
    if (propertyType !== "All") params.set("type", propertyType);
    if (listingType) params.set("listing", listingType);
    if (searchLocation) params.set("location", searchLocation);
    if (budget !== "all") params.set("max", budget);
    setLocation(`/properties${params.size ? `?${params.toString()}` : ""}`);
  }

  return (
    <div className="min-h-screen overflow-x-hidden bg-[#f8f5ee] text-[#10243a]">
      <PublicHeader />
      <main id="main-content">
        <section className="relative isolate min-h-[710px] overflow-hidden bg-[#081729] text-white lg:min-h-[760px]">
          <img src={heroImage} alt="Contemporary residence with Himalayan landscape" className="absolute inset-0 h-full w-full object-cover object-center opacity-75" />
          <div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(6,20,37,.94)_0%,rgba(6,20,37,.73)_38%,rgba(6,20,37,.24)_78%,rgba(6,20,37,.55)_100%)]" />
          <div className="absolute inset-x-0 bottom-0 h-44 bg-gradient-to-t from-[#081729] to-transparent" />
          <div className="container relative flex min-h-[710px] flex-col justify-end py-16 lg:min-h-[760px] lg:py-20">
            <div className="max-w-3xl"><p className="eyebrow text-[#e5c37d]">Nepal’s considered property guide</p><h1 className="mt-5 font-display text-5xl leading-[.94] tracking-[-.035em] sm:text-6xl lg:text-[5.3rem]">A more <em className="font-light text-[#e5c37d]">considered</em> way to find your place.</h1><p className="mt-6 max-w-xl text-sm leading-7 text-white/75 sm:text-base">From private residences to landmark land, PropNexus brings exceptional Nepal properties into one clear, personal conversation.</p></div>
            <div className="mt-10 max-w-6xl rounded-2xl border border-white/15 bg-[#f8f5ee]/95 p-3 text-[#10243a] shadow-[0_24px_90px_rgba(0,0,0,.28)] backdrop-blur-md lg:p-4"><div className="grid gap-2 lg:grid-cols-[.85fr_1fr_1.2fr_1fr_auto] lg:items-end"><div className="rounded-xl px-3 py-2"><label className="catalog-label">Looking to</label><div className="mt-2 flex gap-1 rounded-lg bg-[#e6e0d4] p-1"><button onClick={() => setListingType("Sale")} className={`flex-1 rounded-md py-2 text-[11px] font-bold ${listingType === "Sale" ? "bg-[#10243a] text-white" : "text-slate-500"}`}>Buy</button><button onClick={() => setListingType("Rent")} className={`flex-1 rounded-md py-2 text-[11px] font-bold ${listingType === "Rent" ? "bg-[#10243a] text-white" : "text-slate-500"}`}>Rent</button></div></div><div className="rounded-xl px-3 py-2"><label className="catalog-label">Property type</label><select value={propertyType} onChange={event => setPropertyType(event.target.value)} className="mt-2 h-9 w-full bg-transparent text-sm font-semibold outline-none"><option>All</option><option>House</option><option>Apartment</option><option>Land</option><option>Commercial</option></select></div><div className="rounded-xl px-3 py-2"><label className="catalog-label">Location</label><div className="mt-2 flex items-center gap-2"><MapPin className="h-4 w-4 text-[#b78c43]" /><input value={searchLocation} onChange={event => setSearchLocation(event.target.value)} placeholder="Kathmandu, Chitwan..." className="min-w-0 flex-1 bg-transparent text-sm font-semibold outline-none placeholder:font-normal placeholder:text-slate-400" /></div></div><div className="rounded-xl px-3 py-2"><label className="catalog-label">Maximum budget</label><select value={budget} onChange={event => setBudget(event.target.value)} className="mt-2 h-9 w-full bg-transparent text-sm font-semibold outline-none"><option value="all">Any budget</option><option value="10000000">Up to Rs. 1 crore</option><option value="30000000">Up to Rs. 3 crore</option><option value="999999999">Above Rs. 3 crore</option></select></div><button onClick={beginSearch} className="flex h-12 items-center justify-center gap-2 rounded-xl bg-[#b98d43] px-6 text-xs font-extrabold uppercase tracking-[.13em] text-[#10243a] transition hover:-translate-y-0.5 hover:bg-[#d8b66f]"><Search className="h-4 w-4" /> Search</button></div></div>
          </div>
        </section>
        <section className="border-b border-[#10243a]/10 bg-[#0b1c2f] text-white"><div className="container grid divide-y divide-white/10 py-2 sm:grid-cols-3 sm:divide-x sm:divide-y-0"><div className="flex items-center gap-3 py-4 sm:px-5"><ShieldCheck className="h-5 w-5 text-[#e5c37d]" /><p className="text-[11px] font-semibold uppercase tracking-[.13em] text-white/75">Clear property detail</p></div><div className="flex items-center gap-3 py-4 sm:px-5"><CheckCircle2 className="h-5 w-5 text-[#e5c37d]" /><p className="text-[11px] font-semibold uppercase tracking-[.13em] text-white/75">Responsive viewing support</p></div><div className="flex items-center gap-3 py-4 sm:px-5"><Sparkles className="h-5 w-5 text-[#e5c37d]" /><p className="text-[11px] font-semibold uppercase tracking-[.13em] text-white/75">Personal guidance, locally</p></div></div></section>
        <section className="container py-20 sm:py-28"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div className="max-w-xl"><p className="eyebrow text-[#a67e35]">Selected with intent</p><h2 className="mt-4 font-display text-4xl leading-tight sm:text-5xl">A closer look at what is <em className="font-light">possible.</em></h2></div><Link href="/properties" className="group flex items-center gap-2 text-xs font-bold uppercase tracking-[.14em] text-[#8f6b2f]">Explore the catalogue <ArrowUpRight className="h-4 w-4 transition group-hover:translate-x-1 group-hover:-translate-y-1" /></Link></div><div className="mt-10 grid gap-6 lg:grid-cols-3">{propertiesQuery.isLoading ? Array.from({ length: 3 }, (_, index) => <div key={index} className="h-[460px] animate-pulse rounded-[1.35rem] bg-[#e9e4d8]" />) : propertiesQuery.isError ? <div role="alert" className="lg:col-span-3 rounded-2xl border border-rose-200 bg-rose-50 px-6 py-14 text-center"><p className="font-display text-3xl">Featured properties are temporarily unavailable.</p><p className="mt-3 text-sm text-slate-600">Please try again, or browse the full catalogue shortly.</p><button onClick={() => propertiesQuery.refetch()} className="mt-6 rounded-full bg-[#10243a] px-5 py-2.5 text-xs font-bold text-white">Try again</button></div> : featured.map(property => <PropertyCard key={property.id} property={property} />)}</div></section>
        <section id="why-propnexus" className="overflow-hidden bg-[#e7e1d5] py-20 sm:py-28"><div className="container grid gap-12 lg:grid-cols-[1.15fr_.85fr]"><div><p className="eyebrow text-[#a67e35]">Why PropNexus</p><h2 className="mt-4 max-w-xl font-display text-4xl leading-tight sm:text-5xl">Real estate, <em className="font-light">made more human.</em></h2><p className="mt-6 max-w-xl text-sm leading-7 text-slate-600">You are not simply looking at square metres and price points. You are choosing the setting for a business, a family, or an entirely new pace of life. We keep the process calm, clear, and locally informed.</p><a href={propNexusWhatsAppUrl} target="_blank" rel="noreferrer" className="mt-8 inline-flex items-center gap-2 rounded-full bg-[#10243a] px-5 py-3 text-xs font-bold text-white transition hover:bg-[#b98d43] hover:text-[#10243a]">Talk with Abhay <ChevronRight className="h-4 w-4" /></a></div><div className="grid gap-4"><article className="rounded-2xl border border-[#10243a]/10 bg-[#f8f5ee] p-6"><Building2 className="h-6 w-6 text-[#a67e35]" /><h3 className="mt-7 font-display text-2xl">Relevant detail</h3><p className="mt-2 text-sm leading-6 text-slate-600">Road access, orientation, land area, parking, and amenities are easy to find and easy to compare.</p></article><article className="rounded-2xl border border-[#10243a]/10 bg-[#f8f5ee] p-6"><TreePine className="h-6 w-6 text-[#a67e35]" /><h3 className="mt-7 font-display text-2xl">Context matters</h3><p className="mt-2 text-sm leading-6 text-slate-600">A search begins with the neighbourhood, landscape, and way you want to live—not just an address.</p></article></div></div></section>
        <section className="container py-20 sm:py-28"><div className="flex items-end justify-between gap-5"><div><p className="eyebrow text-[#a67e35]">Just listed</p><h2 className="mt-4 font-display text-4xl sm:text-5xl">Recent opportunities</h2></div><Link href="/properties" className="hidden items-center gap-2 text-xs font-bold uppercase tracking-[.14em] text-[#8f6b2f] sm:flex">View all <ArrowDownRight className="h-4 w-4" /></Link></div><div className="mt-10 grid gap-6 md:grid-cols-2 xl:grid-cols-3">{recent.map(property => <PropertyCard key={property.id} property={property} compact />)}</div></section>
        <section className="bg-[#0a1b2f] py-16 text-white"><div className="container flex flex-col gap-7 sm:flex-row sm:items-end sm:justify-between"><div className="max-w-2xl"><p className="eyebrow text-[#e5c37d]">Ready when you are</p><h2 className="mt-4 font-display text-4xl leading-tight sm:text-5xl">Your next property conversation starts here.</h2></div><a href={propNexusWhatsAppUrl} target="_blank" rel="noreferrer" className="inline-flex w-fit items-center gap-3 rounded-full bg-[#d7b16c] px-6 py-3.5 text-xs font-bold uppercase tracking-[.13em] text-[#10243a] transition hover:-translate-y-0.5 hover:bg-[#f0ce89]">WhatsApp PropNexus <ArrowUpRight className="h-4 w-4" /></a></div></section>
      </main><PublicFooter />
      <a href={propNexusWhatsAppUrl} target="_blank" rel="noreferrer" aria-label="Chat with PropNexus on WhatsApp" className="fixed bottom-5 right-5 z-40 grid h-12 w-12 place-items-center rounded-full bg-[#24c768] text-white shadow-[0_12px_30px_rgba(0,0,0,.28)] transition hover:-translate-y-1"><span className="text-lg font-black">W</span></a>
    </div>
  );
}
