import PublicFooter from "@/components/PublicFooter";
import PublicHeader from "@/components/PublicHeader";
import { formatNpr, Property, propertyStatusClass, resolveGalleryState } from "@/lib/property";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, Bath, BedDouble, CalendarDays, CarFront, Check, ChevronLeft, ChevronRight, Compass, Expand, FileText, MapPin, MessageCircle, Phone, Ruler, Send, SquareStack, TreePine } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { Link, useRoute } from "wouter";

const whatsappNumber = "9779769279600";

export default function PropertyDetail() {
  const [, params] = useRoute("/properties/:slug");
  const slug = params?.slug ?? "";
  const detailQuery = trpc.properties.bySlug.useQuery({ slug }, { enabled: Boolean(slug) });
  const property = detailQuery.data as Property | undefined;
  const [activeImage, setActiveImage] = useState(0);
  const [name, setName] = useState("");
  const [phone, setPhone] = useState("");
  const [message, setMessage] = useState("");
  const [submitted, setSubmitted] = useState(false);
  const inquiryMutation = trpc.inquiries.create.useMutation({ onSuccess: () => { setSubmitted(true); setName(""); setPhone(""); setMessage(""); } });
  const galleryState = resolveGalleryState(detailQuery.data?.imageUrls, detailQuery.data?.featuredImage, activeImage);
  const safeImages = galleryState.images;

  useEffect(() => setActiveImage(0), [detailQuery.data?.id]);
  useEffect(() => {
    setActiveImage(current => Math.min(current, Math.max(safeImages.length - 1, 0)));
  }, [safeImages.length]);

  function sendInquiry(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (!property) return;
    setSubmitted(false);
    inquiryMutation.mutate({ propertyId: property.id, name, phone, message: message || `I would like to enquire about ${property.title}.` });
  }

  if (detailQuery.isLoading) return <div className="min-h-screen bg-[#081729] text-white"><PublicHeader /><div className="container grid min-h-[60vh] place-items-center"><div className="h-10 w-10 animate-spin rounded-full border-2 border-[#d7b16c] border-t-transparent" /></div></div>;
  if (detailQuery.isError) return <div className="min-h-screen bg-[#f8f5ee]"><PublicHeader /><main id="main-content" className="container grid min-h-[55vh] place-items-center py-20 text-center"><div role="alert"><p className="eyebrow text-[#a67e35]">Connection interrupted</p><h1 className="mt-4 font-display text-5xl">We could not load this property.</h1><p className="mx-auto mt-4 max-w-md text-sm leading-7 text-slate-600">Please retry, or return to the property catalogue while we restore the connection.</p><div className="mt-7 flex flex-wrap justify-center gap-3"><button onClick={() => detailQuery.refetch()} className="rounded-full bg-[#10243a] px-5 py-3 text-xs font-bold text-white">Try again</button><Link href="/properties" className="inline-flex items-center gap-2 rounded-full border border-[#10243a]/15 px-5 py-3 text-xs font-bold text-[#10243a]"><ArrowLeft className="h-4 w-4" /> All properties</Link></div></div></main></div>;
  if (!property) return <div className="min-h-screen bg-[#f8f5ee]"><PublicHeader /><main id="main-content" className="container grid min-h-[55vh] place-items-center py-20 text-center"><div><p className="eyebrow text-[#a67e35]">Property unavailable</p><h1 className="mt-4 font-display text-5xl">This listing could not be found.</h1><Link href="/properties" className="mt-7 inline-flex items-center gap-2 rounded-full bg-[#10243a] px-5 py-3 text-xs font-bold text-white"><ArrowLeft className="h-4 w-4" /> Return to properties</Link></div></main></div>;

  const whatsappText = encodeURIComponent(`Hello Abhay, I would like to enquire about ${property.title} on PropNexus.`);
  const image = galleryState.image || property.featuredImage;
  const nextImage = () => safeImages.length > 1 && setActiveImage(current => (current + 1) % safeImages.length);
  const previousImage = () => safeImages.length > 1 && setActiveImage(current => (current - 1 + safeImages.length) % safeImages.length);
  const specItems = [
    { icon: Ruler, label: "Area", value: property.areaSize }, { icon: CarFront, label: "Parking", value: `${property.parkingSpaces || "No"} spaces` },
    { icon: Compass, label: "Orientation", value: property.facingDirection || "On request" }, { icon: TreePine, label: "Road access", value: property.roadAccess || "On request" },
  ];

  return <div className="min-h-screen bg-[#f8f5ee] text-[#10243a]"><PublicHeader />
    <main id="main-content">
      <section className="container py-6 sm:py-8"><Link href="/properties" className="inline-flex items-center gap-2 text-[11px] font-bold uppercase tracking-[.15em] text-[#8e6b32] hover:text-[#10243a]"><ArrowLeft className="h-4 w-4" /> All properties</Link>
        <div className="mt-5 grid gap-7 lg:grid-cols-[minmax(0,1.28fr)_360px] lg:items-end"><div><div className="flex flex-wrap gap-2"><span className="rounded-full bg-[#d7b16c] px-3 py-1 text-[9px] font-extrabold uppercase tracking-[.14em] text-[#0c1c2e]">For {property.listingType}</span><span className={`rounded-full px-3 py-1 text-[9px] font-extrabold uppercase tracking-[.14em] ${propertyStatusClass(property.status)}`}>{property.status}</span></div><h1 className="mt-4 max-w-4xl font-display text-4xl leading-tight sm:text-6xl">{property.title}</h1><p className="mt-4 flex items-center gap-2 text-sm text-slate-500"><MapPin className="h-4 w-4 text-[#a67e35]" />{property.location}, {property.city}</p></div><div className="rounded-2xl bg-[#0a1b2f] p-5 text-white"><p className="text-[10px] font-bold uppercase tracking-[.15em] text-[#e5c37d]">Guiding price</p><p className="mt-3 font-display text-3xl">{formatNpr(property.price, property.listingType)}</p><p className="mt-2 text-xs text-white/55">A PropNexus advisor can provide full documentation and current availability.</p></div></div>
      </section>
      <section className="container"><div className={`grid gap-3 ${safeImages.length > 1 ? "lg:grid-cols-[minmax(0,1fr)_165px]" : ""}`}><div className="relative overflow-hidden rounded-2xl bg-[#0a1b2f]">{image ? <img src={image} alt={`${property.title} view ${activeImage + 1}`} className="aspect-[16/9] w-full object-cover" /> : <div className="grid aspect-[16/9] place-items-center text-sm text-white/65">Property imagery is available on request.</div>}<div className="absolute inset-0 bg-gradient-to-t from-[#081729]/45 via-transparent to-transparent" />{safeImages.length > 1 && <><button onClick={previousImage} className="absolute left-4 top-1/2 grid h-10 w-10 -translate-y-1/2 place-items-center rounded-full bg-[#f8f5ee]/90 text-[#10243a] transition hover:bg-[#d7b16c]" aria-label="Previous image"><ChevronLeft className="h-5 w-5" /></button><button onClick={nextImage} className="absolute right-4 top-1/2 grid h-10 w-10 -translate-y-1/2 place-items-center rounded-full bg-[#f8f5ee]/90 text-[#10243a] transition hover:bg-[#d7b16c]" aria-label="Next image"><ChevronRight className="h-5 w-5" /></button></>}<span className="absolute bottom-4 right-4 flex items-center gap-2 rounded-full bg-[#081729]/80 px-3 py-1.5 text-[10px] font-bold text-white backdrop-blur"><SquareStack className="h-3.5 w-3.5" /> {safeImages.length ? `${activeImage + 1} / ${safeImages.length}` : "Images on request"}</span></div>{safeImages.length > 1 && <div className="grid grid-cols-3 gap-3 lg:grid-cols-1">{safeImages.map((imageUrl, index) => <button key={imageUrl} onClick={() => setActiveImage(index)} className={`relative overflow-hidden rounded-xl bg-[#0a1b2f] ${activeImage === index ? "ring-2 ring-[#c59a4a] ring-offset-2 ring-offset-[#f8f5ee]" : "opacity-65 hover:opacity-100"}`}><img src={imageUrl} alt={`Property thumbnail ${index + 1}`} className="aspect-[4/3] w-full object-cover" />{index === 2 && <span className="absolute inset-0 grid place-items-center bg-[#081729]/45 text-white"><Expand className="h-5 w-5" /></span>}</button>)}</div>}</div></section>
      <section className="container grid gap-10 py-14 lg:grid-cols-[minmax(0,1fr)_360px] lg:py-20"><div><div className="grid grid-cols-2 gap-px overflow-hidden rounded-2xl border border-[#10243a]/10 bg-[#10243a]/10 sm:grid-cols-4">{specItems.map(spec => <div key={spec.label} className="bg-[#f8f5ee] p-5"><spec.icon className="h-5 w-5 text-[#aa8037]" /><p className="mt-5 text-[10px] font-bold uppercase tracking-[.14em] text-slate-500">{spec.label}</p><p className="mt-1 text-sm font-semibold text-[#10243a]">{spec.value}</p></div>)}</div><div className="mt-12"><p className="eyebrow text-[#a67e35]">The property</p><h2 className="mt-4 font-display text-4xl">A place with <em className="font-light">possibility.</em></h2><p className="mt-6 max-w-3xl whitespace-pre-line text-sm leading-8 text-slate-600">{property.description}</p></div><div className="mt-12"><p className="eyebrow text-[#a67e35]">Key features</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{property.amenities.map(item => <div key={item} className="flex items-center gap-3 rounded-xl border border-[#10243a]/10 bg-white px-4 py-3 text-sm font-medium"><span className="grid h-6 w-6 place-items-center rounded-full bg-[#e9ddc4] text-[#8e6b32]"><Check className="h-3.5 w-3.5" /></span>{item}</div>)}</div></div><div className="mt-12 rounded-2xl border border-[#10243a]/10 bg-[#e8e0d2] p-7"><div className="flex items-start gap-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-[#10243a] text-[#e8c979]"><MapPin className="h-5 w-5" /></span><div><p className="font-display text-2xl">Location context</p><p className="mt-2 text-sm leading-6 text-slate-600">Located in {property.location}, {property.city}. Request the full location pin and a convenient site-visit time from our local advisor.</p></div></div></div></div>
        <aside className="lg:sticky lg:top-6 lg:h-fit"><div className="rounded-2xl bg-[#0b1c2f] p-6 text-white shadow-[0_18px_55px_rgba(8,23,41,.18)]"><p className="eyebrow text-[#e5c37d]">Private enquiry</p><h2 className="mt-3 font-display text-3xl">Arrange a closer look.</h2><p className="mt-3 text-xs leading-6 text-white/65">Send your details and Abhay will respond about availability, documentation, or a viewing.</p><a href={`https://wa.me/${whatsappNumber}?text=${whatsappText}`} target="_blank" rel="noreferrer" className="mt-6 flex h-12 items-center justify-center gap-2 rounded-xl bg-[#d7b16c] text-xs font-extrabold uppercase tracking-[.12em] text-[#10243a] transition hover:bg-[#f0ce89]"><MessageCircle className="h-4 w-4" /> Chat on WhatsApp</a><div className="my-6 h-px bg-white/10" /><form onSubmit={sendInquiry} className="grid gap-4"><div><label className="detail-label" htmlFor="inquiry-name">Your name</label><input required id="inquiry-name" value={name} onChange={event => setName(event.target.value)} placeholder="Full name" className="detail-input" /></div><div><label className="detail-label" htmlFor="inquiry-phone">Phone number</label><input required id="inquiry-phone" value={phone} onChange={event => setPhone(event.target.value)} placeholder="+977 ..." className="detail-input" /></div><div><label className="detail-label" htmlFor="inquiry-message">Your message</label><textarea id="inquiry-message" value={message} onChange={event => setMessage(event.target.value)} placeholder="I would like to schedule a visit..." rows={4} className="detail-input resize-none py-3" /></div>{submitted && <p className="rounded-lg bg-emerald-400/15 px-3 py-2 text-xs text-emerald-100">Thank you. Your enquiry has been received.</p>}{inquiryMutation.isError && <p className="rounded-lg bg-rose-400/15 px-3 py-2 text-xs text-rose-100">{inquiryMutation.error.message}</p>}<button disabled={inquiryMutation.isPending} className="flex h-11 items-center justify-center gap-2 rounded-xl border border-white/20 text-xs font-bold transition hover:bg-white hover:text-[#0b1c2f] disabled:opacity-60"><Send className="h-4 w-4" /> {inquiryMutation.isPending ? "Sending…" : "Send enquiry"}</button></form><a href="tel:+9779769279600" className="mt-5 flex items-center justify-center gap-2 text-xs text-white/55 hover:text-white"><Phone className="h-3.5 w-3.5" /> +977 9769279600</a></div></aside>
      </section>
      <section className="border-t border-[#10243a]/10 bg-[#e7e0d3]"><div className="container flex flex-col gap-5 py-9 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><CalendarDays className="h-5 w-5 text-[#9d7634]" /><p className="font-display text-2xl">Want to see it in person?</p></div><a href={`https://wa.me/${whatsappNumber}?text=${whatsappText}`} target="_blank" rel="noreferrer" className="inline-flex w-fit items-center gap-2 text-xs font-bold uppercase tracking-[.13em] text-[#8e6b32]">Arrange a viewing <FileText className="h-4 w-4" /></a></div></section>
    </main><PublicFooter />
  </div>;
}
