import { getVerifiedPriceHistory, formatNpr, type Property } from "@/lib/property";

export default function PriceHistoryChart({ property }: { property: Property }) {
  const points = getVerifiedPriceHistory(property);
  if (points.length < 2) return <section aria-labelledby="price-history-title" className="mt-12 rounded-2xl border border-[#10243a]/10 bg-white p-6 sm:p-8"><p className="eyebrow text-[#a67e35]">Price history</p><h2 id="price-history-title" className="mt-3 font-display text-3xl">Verified pricing timeline</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-500">PropNexus has not received two or more verified historical price records for this listing yet. The current guiding price is shown above; ask an advisor for the latest valuation context.</p></section>;
  const min = Math.min(...points.map(point => point.price));
  const max = Math.max(...points.map(point => point.price));
  const span = Math.max(max - min, 1);
  const width = 640;
  const height = 220;
  const line = points.map((point, index) => { const x = (index / (points.length - 1)) * width; const y = height - ((point.price - min) / span) * (height - 24) - 12; return `${x},${y}`; }).join(" ");
  return <section aria-labelledby="price-history-title" className="mt-12 rounded-2xl border border-[#10243a]/10 bg-white p-6 sm:p-8"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="eyebrow text-[#a67e35]">Verified market record</p><h2 id="price-history-title" className="mt-3 font-display text-3xl">Price history</h2></div><p className="text-xs text-slate-500">{points.length} recorded points</p></div><div className="mt-6 overflow-x-auto"><svg viewBox={`0 0 ${width} ${height + 34}`} role="img" aria-label={`Price history for ${property.title}`} className="min-w-[560px] w-full"><line x1="0" y1={height} x2={width} y2={height} stroke="#d9d2c4" /><polyline points={line} fill="none" stroke="#b78c43" strokeWidth="4" strokeLinecap="round" strokeLinejoin="round" />{points.map((point, index) => { const x = (index / (points.length - 1)) * width; const y = height - ((point.price - min) / span) * (height - 24) - 12; return <g key={`${point.date}-${index}`}><circle cx={x} cy={y} r="6" fill="#10243a" stroke="#e5c37d" strokeWidth="3" /><text x={x} y={height + 18} textAnchor={index === 0 ? "start" : index === points.length - 1 ? "end" : "middle"} fontSize="11" fill="#64748b">{new Date(point.date).toLocaleDateString("en-NP", { month: "short", year: "numeric" })}</text></g>; })}</svg></div><div className="mt-3 flex flex-wrap gap-4 text-xs text-slate-500">{points.map(point => <span key={point.date}><strong className="text-[#10243a]">{new Date(point.date).toLocaleDateString("en-NP", { month: "short", year: "numeric" })}</strong> · {formatNpr(point.price, property.listingType)}</span>)}</div></section>;
}
